apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-node-server
  namespace: scat
  labels:
    purpose: node-server
spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: node-server
  template:
    metadata:
      namespace: scat
      labels:
        purpose: node-server
    spec:
      containers:
      - name: node-server
        image: pswargam/nodeserver
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
