version: "3"
services:
  db1:
    image: bitnami/postgresql:latest
    volumes:
      - pgdata:/bitnami/postgresql
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - webnet
    visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
volumes:
  pgdata:
networks:
  webnet:
     external:
      name: post_webnet
