apiVersion: v1
kind: Service
metadata:
  name: nodeserver
spec:
  selector:
    purpose: nodeserver
  type: NodePort
  ports:
    - name: http
      nodePort: 31002
      port: 4000
      targetPort: 4000
      protocol: TCP