apiVersion: v1
kind: Service
metadata:
  name: serviceNodeServer
spec:
  selector:
    purpose: nodeServer
  type: NodePort
  ports:
    - name: http
      nodePort: 31003
      port: 4000
      targetPort: 4000
      protocol: TCP
