version: "3"
services:
  scatconsumer:
    image: "nawazkh/consumer:latest"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # network_mode: "host"
    networks:
      - webnet
networks:
  webnet:
    external:
      name: post_webnet
