# Generated by Django 2.0.5 on 2018-11-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonMicroserviceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='timeTaken',
            field=models.IntegerField(default=0),
        ),
    ]
